### ISSUE TITLE
CUDA, IPPCV

### ISSUE THREAD

**Issue by sdvillal** [loopbio/opencv-feedstock#1]
Now that we are building packages with gpu support, it should be possible and fairly simple to have gpu-enabled builds of opencv (add the corresponding cmake flag, use our CUDA docker image and declare dependency on cuda80).

Related, we could enable some other optimizations, like ippcv (naively, we would only need to set the corresponding cmake flag).

**Comment by nzjrs** [comment]
Note to John: Give Santi the build flags I am using for the deb packages.

Related: how aggressive should we be with cpu features?

**Comment by sdvillal** [comment]
Closing this as it already happened.
